apiVersion: extensions.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: f5
  namespace: shoot--local--local
spec:
  type: f5-loadbalancer
  providerConfig:
    spec:
      enablePerShootControlPlaneVIP: false
      enableApplicationLB: true

      ccpApiEndpoint: "https://n1devcmp-user.airteldev.com/"
      tenantOrPartition: "qa-tenant"

      vpcId: "ff1067a7-3582-447d-a325-244d89c36cd5"
      vpcName: "vpc-27oct"
      networkId: "86dd3898-e0c8-4bd7-a845-1de8bc41fa83"
      flavorId: 25

      credentialsSecretRef:
        name: cmp-f5-credentials
        namespace: shoot--local--local

      cis:
        bridgeImage: "registry.local.gardener.cloud:5001/extensions/f5:v0.1.0-dev-gardener-1.139.2-fix10"