apiVersion: extensions.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: f5
  namespace: shoot--local--local
spec:
  type: f5-loadbalancer
  providerConfig:
    spec:
      enablePerShootControlPlaneVIP: false
      enableApplicationLB: true

      ccpApiEndpoint: "https://n1devcmp-user.airteldev.com/"
      tenantOrPartition: "qa-tenant"

      vpcId: "ff1067a7-3582-447d-a325-244d89c36cd5"
      vpcName: "vpc-27oct"
      networkId: "b4ca8d86-b6f2-400e-9cb4-c3be9c2d8bad"
      flavorId: 25
      region:  "dev"
      
      credentialsReferenceName: cmp-f5-credentials

      cis:
        bridgeImage: "registry.local.gardener.cloud:5001/extensions/f5:v0.1.0-dev-gardener-1.139.2-fix8"