apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gardener-extension-f5.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "gardener-extension-f5.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "gardener-extension-f5.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "gardener-extension-f5.name" . }}
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-runtime-apiserver: allowed
        networking.gardener.cloud/to-private-networks: allowed
        networking.gardener.cloud/to-public-networks: allowed
        networking.resources.gardener.cloud/to-all-shoots-kube-apiserver-tcp-443: allowed
{{ include "gardener-extension-f5.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | default (include "gardener-extension-f5.name" .) }}
      containers:
        - name: controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
{{ range $name, $value := .Values.controller.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
{{- end }}
          ports:
            - containerPort: 8081
              name: health
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
{{- toYaml .Values.resources | nindent 12 }}
