apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: gardener-extension-f5
type: helm
providerConfig:
  chart: |
    H4sIFAAAAAAA/ykAK2FIUjBjSE02THk5NWIzVjBkUzVpWlM5Nk9WVjZNV2xqYW5keVRRbz1IZWxt
    AOx963IbubHw/uZTdHGzFTnx8CKJ9pr5nCrdvKtayWZJWiepVIoFzjRJRBhgFsBQZmRV5df3AOec
    J8yTnAIwdw4vkmV5vYf4YYsE0Gg0Gt2NbqA5ITJAjtLDDxq5ooJ74177aEqkbs1JyL55hNLpdDov
    9vft/51Op/p/Z3f35Tfd3u7uy5ed/d5e75tOt7fX7X0DnccYfF2JlSbym84nj1Wd3FdSSETfozTr
    3ofZboNEUfax0+q0Oo0AlS9ppO1XPyTcAhm3gC+4loIxlDAWEt704PD0B+900OAkxD7U8ldDzyPs
    A4kiRn1iQDdm+ajdVqfxpcnyf6bU7/8ZYTGqxxIAa/b/i97ei+r+773Y3+7/pyjfwuXg+K/eG8rw
    SERzSSdTfYUfdB92O7s9uDwYwOUJCAmE2w9kPKaMEo3gizAifA6EB7lcsNKAjmItpGp820ign1Ef
    uULvNECu6Zii7MNBRPwperutTqMh0QqCIxFz3Yduo+HLQPUbAJQrTRjrg5YxNhqEodS24ltATkYM
    gz4o1KCFbWH+DzBiYg4EBlKEqKcYq4uYIRxdwI7EX2IqUUGU1XkiQkm0kEA56CmCz2KlUT5rNSAf
    Y0yYQjssCQJqBBZhZ2SETPWNKJQEmP1kqjGw6EyxisEOtiYtUxcS7U9hLmJZaAIKGfpauJEXh7m9
    s+P7YXQipZAXROPVVKKaCmYQlMQ37WGn859//3f3GYgxHJ0P4GBwCj5hTIGeEg1hrDSMENCAUDDC
    sZAIlqyUT1pwjGMSM22EMLyGbuc7g8uSITutborRGdHI/fng1atC/eDVK2CuwtBWoS94oICMxAzh
    Zkr9qSXSlE6mXtrOYgJjs0Y5Mt2OStCoHafbaTRucDQV4nojzrCLLHiicCDpCpcoZ9RH2DH8LCJH
    fGYYyUepvZBwMkEJR4ZUY6O10C7Ut3A1xQwI8iASlGugCiROqOEkDFLWypVmCk2ikb8MlYL//Pt/
    QE+pAsHZPNWqyvZLUGsbRECM/om+Vm7s83Q93ZTTBTWdji6Oi9NUWhKNk7nBTN1Q7U8dn/7FYb6E
    282Ix1T2ISJ6anYjDTAloCbU7PibKSYjXp1dgjKo8ontaCXDNc6BSITQ7G0MHNrvZihlCuovJ4c/
    vnv30/Do5OJqeHx6AchnMCPSCB2zggb+nyBImIEqaOswal9/r7yE6p4ZFGU7GdszYzuOSbFvNpNP
    547uhk9KnOJLNCJt+VqDRCVi6VtGIrEWXiTFjFrSXp1dtizABQICUKVilBc4dkMCOKtIIRsrOuEY
    eK5FUntNedCHIyeCTl2NNaRSitm5jGPGFr5s0JBM0AwjMRKKaiHnfcBYigi9QPjXKFvR9aQV4Kyd
    Kf1ICsNN7SgeMepn37czTlXtca8BoMmkbzez0g2AKGZsIBj15304Hb8VeiBRIdeNhnKceuD7VpQb
    qlvKJgI8nX69UdiQI+K7LZwI4YMgpLxvWIxbAM9hRI0MKWyKZCizLEknj5heVnUgCYwgNM0ZEqW9
    SNIZZTjBlMYXgqHjyZ8QI7dw1o6NpAhiK1JbcGnkiBEidmsSBUbcK+0ZnpAaAhzFk4nhelQ+iRCm
    Rr5bBixNw3FFI+Ukq8cYDanTaAAhhnbNdnsvzqldx19iVGmtH8VG1nXCUtvu7vfntNHIjfC+3ciz
    lMPNnpyhdFxsmNXM7eh80D46KiiHZIoCmmaaTTdPysHwillzA5FKwUPkWiWQ831v9Ewm+GKFhj6G
    wT3H4XZPpdvohuopcAFHBzCKecCsJBnTSSydbAB40xuevr08Ofr54mR4+dPpYHh1djl8f3Jx+uZv
    js/d8AMjkMxehMHJeQHcmDK3gHbWc7MqCY52yoYeBXxaCbRzy0MEjiwy5yQywucSfYk6FXUZpAMr
    16xuMeJaC6BaOflmxWQK8+QDCSOGfWij9ttKsbYfRp5P2j5p+VKnkz06GB7+/Pb47GQ4OLj6sTjF
    d4kS6kMkcUw/mP8i5ImBQRjLNLwZViX2RbNNItqedZvPMnr+eHU1GB4MToeDi5M3p3+tH4ML7oWx
    JsYQMNw/wpQBzZraIWeE0cCsYkpNX3COvqYzqp0dSOJ8/on6Vlb8KzJG2Pnh5Araz2AUa/AJN4pL
    OBEWmA0uYErNIlxzccNhioTpacZY5ckMLt4dFgi2WHV+cvXju+P6mSrKJww9w/lwdkjIZTaIspyT
    bCYvYoQjvKdSx4RZeYMS4kih1O0AGebsc4ZkhoBhpOdmGrFyGyPVWWHMNPWUxgjODhO59Z///1/v
    Twfm30sYM3FTnt/RYPj+cnjy9tLsAjPN4dXJ+eDs4OpkYb6u6fHJ2cnVZk0TqEUKKcQgwevs8Kgi
    SxaMgrckxFSsJntkwcAxcl5FxOhLY3caS01ZdvUl2kMAYYkJc+FscmspqD4coXcQ6ynsCGnoKA2g
    dkSUuhEyePYcEo3l0eA5CDkhnCor2DzT0EAc0QmNHFpvrbJpjnue3Xn5yM1ESDqjuiSQyyK5KmjN
    N2WxnAjmXiKX8w4v9s/pV+DGqD//awwjq+7bwymyCKVq6ejBroA15/9ub796/n/5cuv/e5pye+sZ
    OUU5QrOWF1pmYzXBu7trJG2tTGs5F7GVBa33zl1UtEnhozGZuA8v9uyfNLyMx0aJNb0cGPLA/t1Y
    j0Vq8+ad6TgbuGoQZ22WNtgIO2MLph9+Z7pD/zVQ7rM4WEOtVhHLxIBQCYzWBRpjFB3tMkxL394b
    vUhSrsfQ/E5536lmBZob9z4LsuzvDRbKOUIcSBJFret4hJKjRtWiou3s/9vbTclYC8R6hbjvAJWn
    WtvenecCbzQv90iP/Hd3jSmysKWmbd9wtW1VpWiB33eSD4mnHD6aIxczyq75xyY0h81nUKHbl97l
    y8ta+Z8afZ+gANbFf/ZfdMryf7fT2Xuxlf9PUdZv6JQBcinR/kPjDaEMxkRpEOaobdsA5VGsVavx
    h3ZR/E007DDk5Y1qbcNnRhalLccG4k6665K2BTvy99+p3wNV8F0AZpOqP8FP2SbPm6nMxfn/Xhvo
    tmmrWTP4UqSerZSAX3q9Hrus2/+JC0MKhiPKA8on948Krdn/+7u9vcr+3+329rb7/ymK28/mBLvM
    PWY9086NF0DMrbNajojfKnq3Xlv/GFXWL7JT9IM9a8Ef2rk04EJnVtkCFKe+84C0bUBiPRWS/sse
    81rX31uVPus2Sr5Sg2gjRE0Cokk/czSuNzRyu9IaG5AEcvqN9V1TS6cFH4Fyc7aEfQNDxgyTIFUW
    FzvJTsYHg1NLUYkkyA/M6jn4DIkEF44yDQnnQts/n0McWb+L0kTH9tzsAYnoD1LEkerD35s5nFaK
    a8tnIg6a/0jOrOkRt9Q4qZ2hHNmaCermc2gyquz/N2b9zB9uePNXZL/6x6Nh0HZTWoJI3bjfwpue
    DW4YIprVA0bH6M99hiBuOEo1pVENica91r1wHPeYIMGIMGNpSuel3JhgbrvUTeE5NJ3vqI6Ij4Lj
    Q0h6JCQW9Wk2Sg0h6xBR1t+yGXlq5l0P0hrnnwXmEhJtwOZ1ULkIFtF8EH44Q75IxZyZikt2hiRA
    CTZobATj4gi+EDKgvCg36wa19s8jc3ZqMd3dNTzP+wSZfuhsjl+NaBcMk2BeSuoVM2pUAnpWSQFU
    nBe1WjCdZSmmlfS1B/9CmwdQorA+KnYB5b5lIIdvObbWyOOW5vScoF0O9bUSF0PqHtrZ7Hz/zKED
    uQG/eKZ31vpv0PT+VZS19r8MvFo1c49jwLr7X3u7uxX7f293b+v/fZJSEUa+DFQruXWVuPBy0U0i
    WjBPFqR2rLQILxLVcoxjyu0VphrZXc9Qq6yfhorQ3g2YOJm7si2A8kWEfcjER5AMnQRtIhZLwpbg
    YVsoyicxI7K+TSO/q/GmdyZIcJhUH+XVRnP+tLTJGVVOrqqpkDZQlcWTPDPkyG9YZWzn52q8hHiz
    LmHRlHST5vbyS5BdsLBfaSHJBMvfxaNKnMu1NHZQEgezX/hTDEneQETIDwan7/cuKxUA7g6vu45U
    +DqS5gijaXEYUwqMVPo+BaS0NIq+WGEpvGnjIpctdlhAEyDlqI0au7AflbiAkFkYFyQ9yK8znx1W
    Wi2jiim+Hx1E9CSJQS/Wr5i0rUROuH4nB0Rqu+HuDWEW+ac181rTCyCk/Az5RE/70K0DauOvjwyW
    o74R8vrx8R0zMhNyFVzKNU6yq1qlvkKGRNsWe7v1A9MwDuuGLUSlXdC6cFdsEYVazoSV3AmZ6FhR
    ZYVkTf0qtoXUKqytWbsYRZvvIRCSWxoDRji+Px3cmx2K/S+QBPPlEEZCMCR8ob5m298fiE9rabtm
    vXnMmBm8JOOLZd3KZbcF68rapRtJGkzw9NNg0AmNfpbswQCiVQJvIwj26vaBnCyhUQqBSEnmS1pQ
    jeHS7itQSDTv5vpn1YLOaHR/oe/uNblrTQ+S1L7g7pL6CgZeRroVZFvD+etknRFpBsTSSkf5pdWM
    KH0lCVd2ald0idxct7+SedyfMfJSzyL3AiGRqOX7YyMQISq1YptvBGORpp8ELle4AdHoabNGuUfj
    S5+ovq6y7vzvHk2EyD/hOeia8/9er/r+c7ezv9/Znv+fopTP95HKz/PH2co/yPta8jdu4t57DP9s
    eqZLHpSpksey+MrMDZg+uUru3xPtT5PnVonkIVF077mmeye91F8+lrIS/IeN4EpyEqJ8UvF/tLXw
    Aq76QBgTN9b3sUEPGXMjSD0SUfee5p79I0lnRhonje47vHuBslnvPDq1CIcw5qmpEFp51/GoMB1P
    +5G3v7+XQ34Qm32fLkHRfVD2hb/9vK5yyB9fFfgo9Q7lL0EKytMZ+9As4GS/auVPheDurr9QrckE
    7u6aVUiDwvufhT7546AisxYepVQxHrw7Hr49OD+5HBwcnVQ0vn2H/EaKcNFeGFNkwZLDsq0bEHPQ
    T/dfKz/m3t6CJHyS3It8Dr+zo0D/de4FzYjYQj4rzyNH/PY2uVlZqU/Qdg0c7I/wSyw0Fq8FljpF
    QmpVJU+2zAMhdR++73xfdR84PNxLiUIVozPkqNRAilHF0ppqHf2AC06myNKq7SD9q1pZP7x17xJ2
    jIzML93jzj50e6U2EUoqgqx2t1OolUgC+iA0Tc/5p2C5EsluGcnMZ2oWTou/kZAVNEpSCx+BJwKi
    u/tVxarW2X/5S2kZM3yYDbja/ut29jrV+1/dvb3u1v57ilKJ/7gX9q30PXElABQKbpSF0cG+kCiM
    pAxzi7H83v1xYvb3sxzNlrUz2lyv86L9mPa3zxQrNKk+yS+2T+XCMnhprL0YxEoi7mlELMewRWaE
    MjKijGrnO8lulNk7HgadPrzpZXfKjsVN6lfED5HsQxzd/lOMXjfvS+/mHbx+Dan8GwvZh164xHBV
    OENJ9bwPvqSa+oSlNnN2b63YOg5DIud9aL7p1SePoQoCccNzY6OUeKZ5NcX6Z8NFGJEIYEoUjBA5
    xFwi8aeGke2zvtC9jCccehBSHmtULXiLN3BpzEXI3nNTPrFvGc8Ok2t37gXjiAn/GoNW8qCwsA6X
    xddzq9ai+lTBU4iBl1iHHhs9BfkrQ3r3W4EVve9P+yv7fhADOOUTiUrB+9MB+BZ/GGFC/ITgtfuE
    jQqmT/0eOSp4+c8O3wptXf2lBfqYzdccGIa+DWOnmn3onHDDzNd5WzAOKk2NEHzdrIv2Np8Xe6Wg
    XjdL2BV6WSRLnRwar9377Oz7RX7pdj7Dfi0/iD07tJd4rRFmF9ftn9tbc75owt0d/M6N7Q465vu7
    u2bpHFFmrDqKLQPnZH4Os71+WMuVKyn9+k327D9n1G6nwql2luUzJYRkblk1Z/ca+VAKEP3aWLCI
    3ONw4AYi64ZInrt31zNgIVHY18l+q6hcz31FOWkD/FDsmN7QUykHhlQpo7jenw7UConph9EqYXk+
    +JFOplmynyU8KonGnXFv6IfRkER0aFNIDLXQhN1KVDHTr5s2wVDz7u+98B/Pso7t7K+dFTBsH/gj
    dFqdTjfv/OeiqyExyWozE+Un60016L3Y0VAoS7xgp2kJAoLXMU1BQa7nRCNmNoVRMZ0Uoln+zYn0
    EcKYQbfTgbu778rzUTYrg8uaQpQuqmzTLuG4ACeSBBiAkMVLDOljsBo5eGFO2D5laNFRJe5K+UGm
    bYYOlSJL/Pn+qu6+gqZC6o0WwuzvyJyQlDZ2fzaDhJiPvdiZjcWESzpTHXCFHjuaon9tOqo0Dwxo
    GqKItXpeWESXtUg9N0tbeBSQM0jN4iayI8nQtURyTKnSYiJJOPwlJlxThjud1qtXRTVTJxiGQeze
    xAyTJGLDUexfoy5Ll2fLuL8ma9hnlhHpdiqlQFM21RnsbLrodbolfx2Ut3u2jMPqsDDL/tgIWJbE
    Dz6iEQf3WALHhaUTAVVwQxkDxcSNPY0k6j1lcuru1zeLbtQv7UL5qss6/9/yE5+3cWh43fvP/ZfV
    +9+93stt/PdJSsX/tyQTUOYQXLwS/ogh47Izquod+aJh5O4jRovXTvOzRJDXjurKNqq8jSovRpWX
    a4FfWZTZF2FIjCj6e3OF6koeOyZG6rLA9OHpD6eD4c+XJxdvD87vEZl2j2F/wvmS6HTNU7p6oVtJ
    ZVaMIi9CvcZ5P8uYtmI+g4PLy7+8uzj+KuaTJn7bIGa/XHP9igL41ccBTxzA3/0qAvgbYPlYAfxl
    TLM8sP9bu2e63v631CGJlvkM8f9OZ7/Xrcb/d19s8z89SVmw/0tGRZIXu2r1ZwZ/5aF4rdH/OeyV
    pzoI/Pa9DOv2f5b+7RN+C2Td/t990VvI/7a/ff/9JCXJ52Y9bzZ3Nn6gSie/QqAF4Af0Y402kZpO
    M0BTwRUEsXTuZx6gbDVOtX0gybMfTnAVCrhYklmmmCZu9fbMU9C1fpNJ2L5gWbf/k99Y+KSfAlqz
    /3dfvuhu8/9+oVLR/+lyFy4Aep7X+Db7eRSbzhs/REKhqvudkYVfQkl+C6cSR3Lek9ZKq+IxfIgJ
    Ok9+kTD145R9hhtATDucLb+imJ0103NsPsn0FLW/v2c/aSInqN3x81X6ZSSFFr5gfbg6GtjlXcIE
    hV9MKTLEt0t/JaVvfxolJPZ6EZvnd+qU/eGFsXBR5ZRHUibIksCrMmT7iwIc3O+gtEu/imJnHsBo
    vhLp7NdXyoxWHKScwiSfyiMyn6eZ+oIMmGfC/8QJBFxliUq8T9mKD+/cWkG5zwC1pWb+54OcJv1q
    MeFu41V+LKjGX7GSyassUDi8LD/H1Ot/Xwaqff8sPUushDX6/8Vur5r/+WVnd3v+f5Kyze+0ze+0
    ze+0ze+0ze+0ze+0WLb5nbb5nR4MY5vfaZvfqaZs8zslZZvfaWmjxfxOX/qctC3bsi3b8lsr/xsA
    AP//B0SIYACIAAA=
  values:
    image:
      repository: registry.local.gardener.cloud:5001/extensions/f5
      tag: v0.1.0-dev-gardener-1.139.2-fix10
    rbac:
      clusterAdmin: true
