apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: gardener-extension-f5
type: helm
providerConfig:
  chart: |
    H4sIFAAAAAAA/ykAK2FIUjBjSE02THk5NWIzVjBkUzVpWlM5Nk9WVjZNV2xqYW5keVRRbz1IZWxt
    AOw923IbubH7zK/o4mYrcuLhRRLlNXOcKt28q1rJZklaJ6lUigXONElEGGAWwFBmbFXl6XzAOecL
    8yWnAMydw4tkWV4nxIMtzgCNRqNv6AYwEyID5Cg9fK+RKyq4N+61j6dE6tachOybRyidTqdzsL9v
    /+90OtX/O7u7L77p9nb3ep3e3sFB55tOt7fX7XwDncfofF2JlSbym84n91Ud3FdSSETfoTTz3ofZ
    boNEUfaz0+q0Oo0AlS9ppO2jHxJugYxbwBdcS8EYShgLCa97cHT2g3c2aHASYh9q+auh5xH2gUQR
    oz4xoBuzvNduq9P40mT5jyn18j8jLEb1WApgjfwf9PYOqvLf673Yyv9TlG/hanDyZ+81ZXgsormk
    k6m+xve6D7ud3R5cHQ7g6hSEBMLtDzIeU0aJRvBFGBE+B8KDXC9YbUBHsRZSNb5tJNDPqY9coXcW
    INd0TFH24TAi/hS93Van0ZBoFcGxiLnuQ7fR8GWg+g0AypUmjPVByxgbDcJQavviW0BORgyDPijU
    oIWtYf4PMGJiDgQGUoSopxiry5ghHF/CjsRfYipRQZS980SEkmghgXLQUwSfxUqjfNZqQN7HmDCF
    tlsSBNQoLMLOyQiZ6htVKAkw+8u8xsCiM8UqBjvYmrTMu5BofwpzEctCFVDI0NfC9bzYzYc7278f
    RqdSCnlJNF5PJaqpYAZBSXxTH3Y6//rn/3afgRjD8cUADgdn4BPGFOgp0RDGSsMIAQ0IBSMcC4lg
    yUr5pAUnOCYx00YJwyvodr4zuCzpstPqphidE43cnw9eviy8H7x8Ccy9MLRV6AseKCAjMUO4nVJ/
    aok0pZOpl9azmMDYzFGOTLejEjRq++l2Go1bHE2FuNmIM+wkC54YHEiawhXKGfURdgw/i8gRnxlG
    8lFqLyScTFDCsSHV2FgttBP1LVxPMQOCPIgE5RqoAokTajgJg5S1cqOZQpNo9C9DpeBf//w/0FOq
    QHA2T62qsu0S1NoGERCjv6Ovlev7Ip1PN+R0Qk2j48uT4jCVlkTjZG4wU7dU+1PHp39ymC/hdtPj
    CZV9iIieGmmkAaYE1IQaib+dYtLj9fkVKIMqn9iGVjPc4ByIRAiNbGPg0H47QylTUH86Pfrx7duf
    hsenl9fDk7NLQD6DGZFG6ZgZNPD/AEHCDFRBW4dR++Z75SVU90ynKNtJ357p23FMin2zmfy6cHQ3
    fFLiFF+iUWnL5xokKhFL3zISibXwIilm1JL2+vyqZQEuEBCAKhWjvMSx6xLAeUUK2VjRCcfAczWS
    tzeUB304dirozL2xjlRKMTuWcczYwsMGDckETTcSI6GoFnLeB4yliNALhH+DshXdTFoBztqZ0Y+k
    MNzUjuIRo372vJ1xqmqPew0ATSZ9K8xKNwCimLGBYNSf9+Fs/EbogUSFXDcaynHqoe9bVW6obimb
    KPB0+PVOYUOOiO9EOFHCh0FIed+wGLcAnsOIGh1SEIqkKzMtSSOPmFbWdCAJjCI01RkSpb1I0hll
    OMGUxpeCoePJnxAjN3HWj42kCGKrUltwZfSIUSJWNIkCo+6V9gxPSA0BjuLJxHA9Kp9ECFOj3y0D
    lobhuKKRcpK1Y4yG1Fk0gBBDO2e7vYMLaufxlxhV+taPYqPrOmGpbnf3+wvaaOROeN8K8izlcCOT
    M5SOiw2zmrEdXwzax8cF45AMUUDTDLPpxkk5GF4xc24gUil4iFyrBHIu98bOZIovVmjoYxjccxxu
    ZSoVo1uqp8AFHB/CKOYBs5pkTCexdLoB4HVvePbm6vT458vT4dVPZ4Ph9fnV8N3p5dnrvzg+d90P
    jEIysgiD04sCuDFlbgLtqOdmVhIc7ZANPQr4tBJoF5aHCBxbZC5IZJTPFfoSdarqMkiHVq9Z22LU
    tRZAtXL6zarJFObpexJGDPvQRu23lWJtP4w8n7R90vKlTgd7fDg8+vnNyfnpcHB4/WNxiG8TI9SH
    SOKYvjf/RcgTB4Mwlll4061K/Itmm0S0Pes2n2X0/PH6ejA8HJwNB5enr8/+XN8HF9wLY02MI2C4
    f4QpA5o5tV3OCKOBmcWUmr7gHH1NZ1Q7P5DE+fgT862s+ldkjLDzw+k1tJ/BKNbgE24Ml3AqLDAC
    LmBKzSTccHHLYYqE6WnGWOXBDC7fHhUItvjq4vT6x7cn9SNVlE8Yeobz4fyIkKusE2U5JxEmL2KE
    I7yjUseEWX2DEuJIodTtABnm7HOOZIaAYaTnZhixcoKR2qwwZpp6SmME50eJ3vrXf//Pu7OB+fcK
    xkzclsd3PBi+uxqevrkyUmCGObw+vRicH16fLozXVT05PT+93qxqArVIIYUYJHidHx1XdMmCU/CG
    hJiq1URGFhwco+dVRIy9NH6n8dSUZVdfol0EEJa4MJfOJ7eegurDMXqHsZ7CjpCGjtIAakdEqVsh
    g2fPIbFYHg2eg5ATwqmyis0zFQ3EEZ3QyKH1xhqb5rjnWcnLe24mStI51SWFXFbJVUVrnpTVcqKY
    e4lezhsc7F/QryCMUb/+1xhG1ty3h1NkEUrV0tGDQwFr1v/d3n51/f/ixTb+9zTlwwfP6CnKEZq1
    vNAygtUE7+6ukdS1Oq3lQsRWF7TeuXBR0SeFj8Zl4j4c7Nk/aXgVj40Ra3o5MOSB/buxHovU580b
    03HWcdUhzuosrbARdsYXTH/8xjSH/iug3GdxsIZarSKWiQOhEhitSzTOKDraZZiWnt4bvUhSrsfQ
    /E5536lmBZrr9z4TsuzvDSbKBUIcSBJFrZt4hJKjRtWiou38/w8fNiVjLRAbFeK+A1Qeam19t54L
    vNG83CJd8t/dNabIwpaatn3D1bZWlaIFft9JfiSRcvhollzMGLvm75vQHDafQYVuX1rKl5e1+j91
    +j7BAKzL/+wfdMr6f7fT2etu9f9TlPUCnTJAriXav2u8JpTBmCgNwiy1bR2gPIq1ajV+1y6qv4mG
    HYa8LKjWN3xmdFFac2wg7qRSl9Qt+JG//U79FqiC7wIwQqr+AD9lQp5XU1mI879eGei2aqtZ0/lS
    pJ6t1IBfer4eu6yT/ySEIQXDEeUB5ZP7Z4XWyP/+bm+vIv+73f2Drfw/RXHybFawy8JjNjLtwngB
    xNwGq+WI+K1idOuVjY9RZeMiO8U42LMW/K6dawMudOaVLUBx5jtPSNsKJNZTIek/7DKvdfO9Nemz
    bqMUKzWINkLUJCCa9LNA43pHI/crrbMBSSKn31jfNPV0WvARKDdrS9g3MGTMMElSZXmx02xlfDg4
    sxSVSIJ8wayeg8+QSHDpKFORcC60/fM5xJGNuyhNdGzXzR6QiP4gRRypPvy1mcNppbi2fCbioPm3
    ZM2aLnFLlZO3M5Qj+2aCuvkcmowq+/+tmT/zh+ve/BXZR397NAzabkhLEKnr91t43bPJDUNEM3vA
    6Bj9uc8QxC1HqaY0qiHRuNe6F47jHhMkGBFmPE3popQbE8yJS90QnkPTxY7qiPgoOD6EpMdCYtGe
    Zr3UELIOEWXjLZuRp2bc9SCtc/5ZYC4h0QZsXgeVi2ARzQfhhzPki1TMmak4ZedIApRgk8ZGMS72
    4AshA8qLerOuU+v/PDJnpx7T3V3D87xP0OlHzuf41ah2wTBJ5qWkXjGiRiWhZ40UQCV4UWsF01GW
    clpJW7vwL9R5ACUK86Nil1DuWwZy+JZza408b2lWzwna5VRfKwkxpOGhnc3W988cOpA78Itreuet
    /xu63r+Kstb/l4FXa2busQxYu/+rl6z/e73OXnf/m87u3u52/f80paKMfBmoVrLrKgnh5aqbRLTg
    nixo7VhpEV4mpuUEx5TbLUw1urueoVZ5Pw0Vod0bMHE6d2VdAOWLCPuQqY8g6TpJ2kQsloQtwcPW
    UJRPYkZkfZ1Gvlfjde9ckOAoeX2cvzaW86elVc6pcnpVTYW0iaosn+SZLkd+wxpjOz73xkuIN+sS
    Fk1JN6luN78E2QYL+0gLSSZYfhaPKnkuV9P4QUkezD7wpxiSvIKIkB8Ozt7tXVVeALg9vG47UuFx
    JM0SRtNiN6YUGKn0PAWktDSGvvjCUnjTykUuW2ywgCZAylEbVXZpPypxASEzMS5JephvZz4/qtRa
    RhVTfD86jOhpkoNefL9i0PYlcsL1WzkgUluBuzeEWeSf1YxrTSuAkPJz5BM97UO3DqjNvz4yWI76
    Vsibx8d3zMhMyFVwKdc4ybZqldoKGRJta+zt1ndMwzis69axzgDl1VQIneTeB4xwfHc2WI7LSAiG
    hDcWKkicPIQFKsRZBCtiTfnkkE2EpHoaru1g4X0oONVCnnGNckbYE5O5kPy/xDFK5D5+Dvb0N53A
    JeCL7S+RBPP1LFB9W6OM7g/EpzWKaqV+NIXHjJnOS5anWFapQVOyPYx1Zc28AIwkDSZ49mkw6IRG
    P8ta/twIQLRKDW8EwW4oP5STJTRKIRApyXxJDaoxXNp8BQqJP7C5VVw1oTMa3d8Uud1WbrPVgwTU
    F9xtnV/BwMtIt4Jsazh/lX/gimdBLH3pKL/0NSNKX0vClR3aNQ3rIa2Tr2Qc92eMvNSzyL1ASCRq
    uXxsBCJEpVaI+UYwFmn6SeBy+xQQjZ42c5THWb70Om9ZWbf+d4cmQuSfcBx0zfp/r1c9/7nb2d/b
    267/n6KU1/eRytfzJ9nMPyj6Woo3bhLee4z4bLqmSw6UqVLEsnjKzHWYHrlK9t8T7U+T41aJjJMo
    uvdYU9lJN/WXl6WsBP9hPbiSrIQon1TiH20tvICrPhDGxK2NfWzQQsbcqCyPRNSdp7ln+0jSmdF7
    SaX7du9OoGzWOs9OLcIhjHnKLKWUdxOPCsPxtB95+/t7OeQHsdn36RQUwwflWPibzxsqh/zwVYGP
    0uhQfhKkYKacWw3NAk72USs/KgR3d/2F15pM4O6uWYU0KJz/WWiTHw4qMmvhUEoV48Hbk+Gbw4vT
    q8Hh8WnFttpzyK+lqFlvjimyoHCwauHdgJglWip/rUwFmXmXhE+SfZHP4Te2F+i/yqOgGRFbyGfl
    ceSIf/iQ7KysvE/QdhUc7I/wSyw0FrcFlhpFQmpVJU82zQMhdR++73xfXW86PNxJicIrRmfIUamB
    FKOKTzPVOvoBF4JMkaVV20H6R/Vlffc2vEvYCTIyv3KHO/vQ7ZXqRCipCLK3u53CW4kkoA9C07Sc
    fwqWK5HslpHMYqZm4rT4CwlZwaIkb+Ej8ERBdHe/qlzVOv8vPyktY4YP8wFX+3/dzl6nuv+ru7e7
    v/X/nqJU8j/uhH0rPU9cSQAlMTxjg30hURhNGeYeY/m8++Pk7O/nORqRtSPa3K7zov+YtrfHFCs0
    qR7JL9ZP9cIyeGmuvZjESjLuaUYsx7BFZoQyMqKMahelyHaU2T0eBp0+vO5le8pOxG0awcP3kexD
    HH34uxi9at6X3s07ePUKUv03FrIPvXCJ46pwhpLqeR98STX1CUt95mzfWrF2HIZEzvvQfN2rvzyG
    KgjELc+djdLFM83rKdYfGy7CiEQAU6JghMgh5hKJPzWMbI/1he5kPOHQg5DyWKNqwRu8BRt5h+w8
    N+UTe5bx/CjZdudOMI6Y8G8waCUHCgvzcFU8PbdqLqpHFTyFGHiJd+ix0VOQv9Kld78ZWNH6/rS/
    tucHMYAzPpGoFLw7G4Bv8YcRJsRPCF4rJ2xUcH3qZaSYUDk/eiO0DaqXJuhjNl6zYBj6No2dWvah
    C3cNs6jih4JzUKlqlOCrZl22t/m82CoF9apZwq7QyiJZauTQeOXOZ2fPF/ml2/kM8lo+EHt+ZDfx
    WifMTq6Tnw8fzPqiCXd38BvXt1vomOd3d83SOqLMWHUUWwbO6fwcZnt9t5YrV1L61evs2H/OqN1O
    hVPtKMtrSgjJ3LJqzu41+qGUivm1sWARucfhwA1U1i2RPA+krmfAwkVhXyf7raJyPfcV9aRN8EOx
    YbpDT6UcGFKljOF6dzZQKzSmH0arlOXF4Ec6mWaX/SzhUUk07ox7Qz+MhiSiQ3uFxFALTdgHiSpm
    +lXTXjDUvPtrL/zbs6xhO/trZwUM2wZ+D51Wp9PNG/+xGGpIXLLam4nylfWmFvRe7GgolF28YIdp
    CQKC1zFNwUCu50SjZjaFUXGdFKKZ/s2J9BHCmEG304G7u+/K41H2VgZ3awpRumiyTb2E4wKcSBJg
    AEIWs+vpYbAaPXhpVtg+ZWjRUSXuSvlBpnWGDpUiS/zx/qbuvoqmQuqNJsLId2RWSEobvz8bQULM
    x57szMdiwl06U+1whR07nqJ/Yxqq9B4Y0DREEWv1vDCJ7tYi9dxMbeFQQM4gNZOb6I7khq4lmmNK
    lRYTScLhLzHhmjLc6bReviyamTrFMAxidyZmmFwiNhzF/g3qsnZ5toz7a24N+8w6IhWn0hVoyl51
    BjubTnqdbclPB+X1ni3jsDoszLQ/NgKWJfG9j2jUwT2mwHFhaUVAFdxSxkAxcWtXI4l5T5mcuv31
    zWIY9UuHUL7qsi7+t3zF522cGl53/nP/xW4l/tfrHWzzv09SKvG/JTcBZQHBxS3hj5gyLgejqtGR
    L5pG7j5itnjtMD9LBnltr65ss8rbrPJiVnm5FfiVZZl9EYbEqKK/NleYruSwY+KkLktMH539cDYY
    /nx1evnm8OIemWl3GPYnnC/JTtccpatXupWrzIpZ5EWoNzjvZzemrRjP4PDq6k9vL0++ivGkF79t
    kLNfbrl+RQn86q71J07g734VCfwNsHysBP4yplme2P/17+i8X1nv/1vqkMTKfIb8f6ez3+tW8/+7
    B9vzn09SFvz/klOR3Itd9fozh79yULzW6f8c/spTLQT+/aMM6+Q/u/7tE74Fsk7+dw96C/e/7W/v
    /3ySktznZiNv9u5sfE+VTr5CoAXge/RjjfYiNZ3eAE0FVxDE0oWfeYCy1TjT9uQezz6c4F4o4GLJ
    zTLFa+JWi2d+BV3r3/ISti9Y1sl/8o2FT/oU0Br5331x0N3e//uFSsX+p9Nd2ADoeV7j2+zzKPY6
    b3wfCYWq7jsjC19CSb6FU8kjuehJa6VX8RgxxASdJ99ImMZxyjHDDSCmDc6Xb1HM1prpOjYfZLqK
    2t/fs780kRPUbvn5Mn0YSaGFL1gfro8HdnqXMEHhiylFhvh26VdS+vbTKCGx24vYPN9Tp+yHF8bC
    ZZVTHkmZILsEXpUh2y8KcHDfQWmXvopiRx7AaL4S6ezrK2VGK3ZSvsIkH8ojMp+nmfqCDJjfhP+J
    Awi4yi4q8T5FFB/euLWCcp8BakvN/M8HOb30q8WE241X+VhQTbxiJZNXWaCweFm+jqm3/74MVPv+
    t/Qs8RLW2P+D/Rcv8vufOvvfdHZfbO9/fqKyvd9pe7/T9n6n7f1O2/udtvc7fUX3Oy0K2faCp3sB
    2V7w9FAA2wue0rK94KlYthc8ZeU/54KnL71825Zt2ZZteXD5/wAAAP//QRBqQwCIAAA=
  values:
    image:
      repository: registry.local.gardener.cloud:5001/extensions/f5
      tag: v0.1.0-dev-gardener-1.139.2-fix8
    rbac:
      clusterAdmin: true
