apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: gardener-extension-f5
type: helm
providerConfig:
  chart: |
    H4sIFAAAAAAA/ykAK2FIUjBjSE02THk5NWIzVjBkUzVpWlM5Nk9WVjZNV2xqYW5keVRRbz1IZWxt
    AOx963IbudHo/uZTdNHZipR4hheJ8po5SpVu3lWtZLMkrZNUKsUCZ5okIsxgFsBQZmRV5dd5gHPO
    E+ZJTgGYO4cX2bK8zkf8sEUCaDQa3Y1GN9CcEOFjiMLBDwpDSXnojHutkykRyp2TgH33BKXdbrcP
    9vfN/+12u/p/u9t99V2n1+2+2m/v9/b3vmt3enudznfQforB15VYKiK+a3/2WNXJfSOFRPQ9Cr3u
    fZh1GySKso9tt+22Gz5KT9BIma9+TLgFMm4Bj4dKcMZQwJgLeNOD4/MfnfNBIyQB9qGWvxpqHmEf
    SBQx6hENujHLR+247cbXJsv/mFIv/zPCYpRPpQDWyP9Bb++gKv+9g/ZW/p+jvIDrwelfnTeU4QmP
    5oJOpuoGP6g+dNvdHlwfDeD6DLgAEpoPZDymjBKF4PEgIuEcSOjnesFoAzqKFRey8aKRQL+gHoYS
    nXMfQ0XHFEUfjiLiTdHpuu1GQ6BRBCc8DlUfOo2GJ3zZbwDQUCrCWB+UiLHRIAyFMhUvAEMyYuj3
    QaICxU0L/b+PEeNzIDAQPEA1xVhexQzh5Ap2BP4aU4ESoqzO4REKorgAGoKaIngslgrFrtuAfIwx
    YRLNsMT3qVZYhF2QETLZ16pQEGDmk65G36AzxSoGO+hOXF0XEOVNYc5jUWgCEhl6ituRF4e5fzDj
    e0F0JgQXV0ThzVSgnHKmERTE0+1hp/2ff//fzi7wMZxcDuBocA4eYUyCmhIFQSwVjBBQg5AwwjEX
    CIasNJy4cIpjEjOllTAcQqf9vcZlyZBtt5NidEEUht588Pp1oX7w+jUwW6FpK9HjoS+BjPgM4W5K
    vakh0pROpk7azmACY71GOTKdtkzQqB2n02407nA05fx2I84wi8zDZMOBpCtco5hRD2FH8zOPLPGZ
    ZiQPhXICEpIJCjjRpBrrXQvNQr2AmylmQDD0I05DBVSCwAnVnIR+ylr5pplCE6j1L0Mp4T///n+g
    plQCD9k83VWl6Zeg1tKIAB/9Ez0l7diX6XraKacLqjudXJ0WpymVIAonc42ZvKPKm1o+/YvFfAm3
    6xFPqehDRNRUSyP1MSWgIlRL/N0UkxFvLq5BalTDieloNMMtzoEIhEDLNvoW7XczFCIF9Zez45/e
    vft5eHJ2dTM8Pb8CDGcwI0IrHb2CGv6fwE+YgUpoqSBq3f4gnYTqjh4URSsZ29FjW45JsW82k0+X
    lu6aT0qc4gnUKm35WoNAyWPhGUYiseJOJPiMGtLeXFy7BuACAQGolDGKKxzbIQGsVSSRjSWdhOg7
    tkVSe0tDvw8nVgWd2xpjSKUUM3MZx4wtfNmgAZmgHkZgxCVVXMz7gLHgETo+925RuNHtxPVx1so2
    /UhwzU2tKB4x6mXftzJOla1xrwGgyKRvhFmqBkAUMzbgjHrzPpyP33I1ECgxVI2GtJx65HlGlWuq
    G8omCjydfr1R2BAj4lkRTpTwkR/QsK9ZLDQAXsKIah1SEIpkKL0sSSeH6F5m60Dia0WomzMkUjmR
    oDPKcIIpja84Q8uTPyNGduGMHRsJ7sdGpbpwrfWIViJGNIkEre6lcjRPCAU+juLJRHM9So9ECFOt
    3w0DlqZhuaKRcpLZxxgNqN3RAAIMzJp1eweX1KzjrzHKtNaLYq3r2kGpbaf7wyVtNHIjvG8EeZZy
    uJbJGQrLxZpZ9dxOLgetk5PC5pBMkUNTT7Np50lD0Lyi11xDpIKHAYZKJpBzudf7TKb4YomaPprB
    HcvhRqZSMbqjagohh5MjGMWhz4wmGdNJLKxuAHjTG56/vT47+eXqbHj98/lgeHNxPXx/dnX+5m+W
    z+3wA62QtCzC4OyyAG5MmV1AM+u5XpUERzNlTY8CPm4C7dLwEIETg8wlibTyuUZPoEpVXQbpyOg1
    s7doda04UCWtfjNqMoV59oEEEcM+tFB5LSlZywsixyMtj7ieUOlkT46Gx7+8Pb04Gw6Obn4qTvFd
    sgn1IRI4ph/0fxGGiYFBGMt2eD2sTOyLZotEtDXrNHczev50czMYHg3Oh4Orszfnf60fI+ShE8SK
    aENAc/8IUwbUa2qGnBFGfb2KKTU9HoboKTqjytqBJM7nn2zf0qh/ScYIOz+e3UBrF0axAo+EeuPi
    VoX5WsA5TKlehNuQ34UwRcLUNGOs8mQGV++OCwRbrLo8u/np3Wn9TCUNJwwdzflwcUzIdTaINJyT
    CJMTMRIivKdCxYQZfYMC4kiiUC0fGebsc4FkhoBBpOZ6GrG0gpHuWUHMFHWkwggujhO99Z///X/e
    nw/0v9cwZvyuPL+TwfD99fDs7bWWAj3N4c3Z5eDi6OZsYb626enZxdnNZk0TqEUKSUQ/wevi+KSi
    SxaMgrckwFStJjKyYOBoPS8jovdLbXdqS00advUEmkMAYYkJc2VtcmMpyD6coHMUqynscKHpKDSg
    VkSkvOPC330JyY7lUP8lcDEhIZVGsTm6oYY4ohMaWbTems2mOe45RvLykZuJkrRGdUkhl1VyVdHq
    b8pqOVHMvUQv5x0O9i/pN+DGqD//Kwwis923hlNkEQrpquiTXQFrzv+d3n71/P/q1db/9zzl/t7R
    eoqGCM1aXnC1YDXBeXhoJG2NTnOti9joAve9dRcVbVL4qE2m0IODPfMnDa7jsd7Emk4ODEPf/N1Y
    j0Vq8+ad6TgbuGoQZ22WNtgIO20Lph9+p7tD/xBo6LHYX0Mtt4hlYkDIBIZ7hdoYRUu7DNPSt49G
    LxI0VGNofi+d72WzAs2O+5gFWfb3BgtlHSEWJIki9zYeoQhRoXQpb1n7//5+UzLWAjFeodCzgMpT
    rW1vz3O+M5qXe6RH/oeHxhRZ4Mppy9NcbVpVKVrg953kQ+Iph4/6yMX0Ztf8YxOaw+YuVOj2taV8
    eVmr/1Oj7zM2gHXxn/2Ddln/d9vtve5W/z9HWS/QKQPkWqL1h8YbQhmMiVTA9VHbtAEaRrGSbuMP
    raL6myjYYRiWBdXYhrtaF6UtxxriTip1SduCHfn77+XvgUr43gctpPJP8HMm5Hkzmbk4/9ehhm6a
    us2awZcitbtSA37t9Xrqsk7+ExeG4AxHNPRpOHl8VGiN/O93e3sV+e929l9t5f85ipVnfYJd5h4z
    nmnrxvMhDo2zWoyI5xa9W4fGP0al8YvsFP1guy78oZVrg5CrzCpbgGK37zwgbRqQWE25oP8yxzz3
    9gezpc86jZKvVCPaCFARnyjSzxyN6w2N3K40xgYkgZx+Y33X1NJx4SPQUJ8tYV/DEDHDJEiVxcXO
    spPx0eDcUFQg8fMDs3wJHkMiwIajdEMShlyZP19CHBm/i1RExebc7ACJ6I+Cx5Hsw9+bORw3xdX1
    GI/95j+SM2t6xC01TmpnKEamZoKq+RKajErz/51eP/2HHV7/FZmv/vFkGLTslJYgUjfuC3jTM8EN
    TUS9esDoGL25xxD4XYhCTmlUQ6Jxz30UjuMe48QfEaYtTWG9lBsTzIpL3RReQtP6juqI+CQ4fgpJ
    T7jA4n6ajVJDyDpEpPG3bEaemnnXgzTG+ReBuYREG7B5HdSQ+4tofhJ+OMNwkYo5MxWX7AKJjwJM
    0FgrxsURPM6FT8Oi3qwb1Ng/T8zZqcX08NBwHOczdPqxtTl+M6qdM0yCeSmpV8yoUQnomU0KoOK8
    qN0F01mWYlpJX3PwL7T5BEoU1kfGNqDcNwxk8S3H1hp53FKfnhO0y6E+N3ExpO6hnc3O97sWHcgN
    +MUzvbXW/wtN799EWWv/C9+p3WYecQxYY//3et2K/7e719072Nr/z1EqysgTvnSTW1eJCy9X3SSi
    BfNkQWvHUvHgKtlaTnFMQ3OFqUZ31zPUKuunISM0dwMmVueubAsgPR5hHzL14SdDJ0GbiMWCsCV4
    mBaShpOYEVHfppHf1XjTu+DEP06qT/JqvXP+vLTJBZVWr8opFyZQlcWTHD3kyGuYzdjMz9Y4CfFm
    HcKiKekkzc3lFz+7YGG+UlyQCZa/i0eVOJdtqe2gJA5mvvCmGJC8AY8wPBqcv9+7rlQA2Du89jpS
    4etI6COMosVhdCkwUun7FJBUQm/0xQpD4U0bF7lsscMCmgApR23U2Ib9qMAFhPTC2CDpUX6d+eK4
    0moZVXTxvOgoomdJDHqxfsWkTSWGJFTvxIAIZQTu0RAKkVEbOC3cV9qQOqspBBn7rqgyglpTv4p0
    kFomtTVrpg0lu+NTICQ3BQaMhPj+fPB4whf6XyHx58shjDhnSMKF+hrWezwQj9bSds16hzFjevCS
    nimWdSuX3VirK2uXbiSoP8Hzz4NBJzT6RbBPBhCtErqNIJjrw0disoRGKQQiBJkvaUEVBku7r0Ah
    0f6b68BVCzqj0aP5f2bv1tirNW+XyPE6CbIXpVcw8DLSrSDbGs5fp+u0StMgllZayi+tZkSqG0FC
    aaZ2Q5fozXXylczj8YyRl3oWeRQIgUQul4+NQAQo5Qox3wjGIk0/CxzAmIuAqD74RKGj9Brlp+qv
    bdVvXtad/+yl+QDDz3gOuOb8t9ervv/rtvf39rfnv+co5fNdJPPz3Gm28p/kfSv5mzZx7zyFfy61
    6ZMHRbLksSq+MrIDpk9ukvvXRHnT5LlNIvUkih4911R20kvd5WMJK8H/tBFsCVHdcXFLw0nl/NtS
    3PFD2QfCGL8zZ98Neog41ErMIRG17yke2T8SdKY1YdLoscPbFwib9c6jE4twCGOOnHKupHMbjwrT
    cZQXOfv7eznkT2KzH9IlKB4fy77Qt1/WVQr545sCH6XegfwlQGHjsoY2NAs4ma/c/KkIPDz0F6oV
    mcDDQ7MKaVB4/7HQJ38cUmTWwqOEKsaDd6fDt0eXZ9eDo5Ozym5r3qG+ETxY3KvHFJm/5KBq6gZE
    TfuZ/Ln5EfP+HgQJJ8m9uJfwOzMK9A9zL1hGRBfDWXkeOeL398nNukp9grZtYGF/hF9jrrB4LazU
    KeJCySp5smUecKH68EP7h05lHIuHvSlfqGJ0hiFKORB8VLFypkpFP+KCkyEytGpZSP+qVtYPb9x7
    hJ0iI/Nr+7ivD51eqU2EgnI/q+22C7UCiU8/CU3dc/45WK5EslNGMvOZ6YVT/G8kYIUdJamFjxAm
    CqLT/aZiFevsv/ylrIgZfpoNuNr+67T32tX7P529bm9r/z1Hqfj/7QtrN31PWgkABDzUm4Xegz0u
    kGtNGeQWY/m989PEbB9nOWqRNTPafF8Pi/Zj2t88U6vQpPoku9g+1QvL4KWx1mIQI4m4phGRHEOX
    zAhlZEQZVdZvkd0oMjF+jU4f3vSyO0Wn/C716eGHSPQhju7/yUeHzcfSu/kAh4eQ6r8xF33oBUsM
    V4kzFFTN++AJqqhHWGozZ/eWiq3jICBi3ofmm1598hAqwed3YW5slBKPNG+mWP9stAgj4j5MiYQR
    YghxKJB4U83I5llXYF9GkxB6ENAwVihdeIt3cK3NRcje89JwYt6yXRwn167sC7YR494t+m7yoKyw
    DtfF11Or1qJ6Vd2RiL6TWIcOGz0H+StDOo9bgRW9H0/7G/N+DH04DycCpYT35wPwDP4wwoT4CcFr
    5YSNCqZPvYycFDzsF8dvuTJu9tICfczmqw8MQ8+EMdOdfWgdYMPMz3hfMA4qTbUSPGzWRfuaL4u9
    UlCHzRJ2hV4GyVIni8ahfZ+bfb/IL532F5DX8oPIi2NzidMYYWZxrfzc3+vzRRMeHuB3dmx70NHf
    Pzw0S+eIMmPVUWwZOKvzc5it9cMarlxJ6cM32bPvnFE77QqnmlmWz5QQkLlh1Zzda/RDKTjzW2PB
    InJPw4EbqKw7IsLctbqeAQuJor5N9ltF5XruK+pJE+CFYsf0hpZMOTCgUuqN6/35QK7QmF4QrVKW
    l4Of6GSaJXtZwqOCKNwZ94ZeEA1JRIcmhcBQcUXYvUAZM3XYNAlmmg9/7wX/2M06trK/dlbAMH3g
    j9B22+1O3vnPRVdDYpLVZqbJT9ab7qCPYkdNoezhvZmmIQjwsI5pChvkek7UamZTGBXTSSLq5d+c
    SB8hiBl02m14ePi+PB9pXuXbrBlEquKWrdslHOfjRBAffeCieIEgfQxUowev9AnbowwNOrLEXSk/
    iLTN0KJSZIk/P36re6yiqZB6o4XQ8h3pE5JU2u7PZpAQ86kXO7OxGLdJR6oDrtjHTqbo3eqOMs0D
    AooGyGMlXxYW0WatkS/10hYuhecMUrO4ie5IMjQt0RxTKhWfCBIMf41JqCjDnbb7+nVxm6lTDEM/
    tm8ihkkSqeEo9m5RlbXL7jLur8ka9YV1RCpOpRRY0qS6gp1NF71ub8lfh+TtdpdxWB0WetmfGgHD
    kvjBQ9Tq4BFLYLmwdCKgEu4oYyAZvzOnkWR7T5mc2vvVzaIb9Wu7UL7pss7/t/zE52wcGl73/m//
    Vbfi/+v1Drbx32cpFf/fkkwwmUNw8UrwE4aMy86oqnfkq4aRO08YLV47zS8SQV47qi3bqPI2qrwY
    VV6+C/zGosweDwKiVdHfmyu2ruSxW2KkLgtMH5//eD4Y/nJ9dvX26PIRkWn7GPJnnC+JTtc8papX
    upVUVsUo8iLUW5z3s4xZK+YzOLq+/su7q9NvYj5p4q8NYvbLd67fUAC/+3UD+N1vIoC/AZZPFcBf
    xjTLA/vf4h3PVWW9/W+oQ5Jd5gvE/9vt/V6nGv/vHmzz/zxLWbD/S0ZFkhe5avVnBn/loXCt0f8l
    7JXnOgj893sZ1sl/lv7rM34LYp38dw96C/m/9rf5H5+lJPm8jOfN5E7GD1SqJAu94oAf0IsVmkRa
    Ks0ATHkowY+FdT+HPgq3ca6AhgrDLHG+rZAQ8iWZRYppwlaLZ56CzP2vTML1Fcs6+U9y7H/WT8Gs
    kf/uq4PONv/rVyqV/T9d7sIFQMdxGi+yn8cw6ZzxQ8QlyrrfmVj4JYzkt1AqcSTrPXFXWhVP4UNM
    0Hn2i4SpH6fsM9wAYtrhYvkVxeysmZ5j80mmp6j9/T3zSRExQWWPn6/TLyPBFfc468PNycAs7xIm
    KPxiRpEhXiz9lYy++WmMgJjrRWye36mTJvH+mNuocsojKRNkScBlGbLJKB+C/R2MVulXMczMfRjN
    VyKd/fpGmdGKg5RTWORTeULmcxSTX5EB80zonzkBP5RZogrnc0Tx0zu7Kyj3BaC6cuZ9Ochp0ieX
    cXsbr/JjMTX+ipVMXmWBwuFl+Tmmfv/3hC9bj8/SssRKWLP/9/Z7+xX7/1W7u83/+Sxlm99nm99n
    m99nm99nDXVWUwi2+X22+X0Wyza/zza/zza/T031Nr9PuXwj+X2+tq2+LduyLdvylOX/BwAA//+2
    idKbAIQAAA==
  values:
    image:
      repository: registry.local.gardener.cloud:5001/extensions/f5
      tag: v0.1.0-dev-gardener-1.139.2-fix2
    rbac:
      clusterAdmin: true
